# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votestatus',
            options={'verbose_name_plural': 'Vote statuses'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.TextField(help_text='Describe why you should be in this role', verbose_name='Description'),
        ),
    ]
