# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20170223_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteballot',
            name='vote_candidate',
        ),
        migrations.AddField(
            model_name='voteballot',
            name='candidates',
            field=models.ManyToManyField(related_name='vote_ballot', to='voting.Candidate', verbose_name="Vote's Candidate"),
        ),
        migrations.AddField(
            model_name='voteballot',
            name='position',
            field=models.CharField(choices=[('P', 'President'), ('A', 'VP of Administration'), ('T', 'Treasurer'), ('S', 'VP of Service'), ('N', 'VP of New Member Services'), ('O', 'VP of Social Affairs'), ('J', 'VP of Standards'), ('R', 'Risk Management'), ('B', 'Standards Board')], default='P', max_length=1),
        ),
    ]
