# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20170223_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteballot',
            name='candidates',
        ),
        migrations.AddField(
            model_name='voteballot',
            name='candidates_json',
            field=models.TextField(default='', verbose_name='Candidates json'),
            preserve_default=False,
        ),
    ]
