# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField(blank=True, null=True, verbose_name='Question 1')),
                ('question_2', models.TextField(blank=True, null=True, verbose_name='Question 2')),
                ('question_3', models.TextField(blank=True, null=True, verbose_name='Question 3')),
                ('question_4', models.TextField(blank=True, null=True, verbose_name='Question 4')),
                ('question_5', models.TextField(blank=True, null=True, verbose_name='Question 5')),
                ('question_6', models.TextField(blank=True, null=True, verbose_name='Question 6')),
                ('question_7', models.TextField(blank=True, null=True, verbose_name='Question 7')),
                ('applicant_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('rating', models.SmallIntegerField(blank=True, null=True, verbose_name='Rating')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='applications.Application', verbose_name='Application')),
                ('reviewer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
        ),
    ]
