# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Is Submitted'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_1',
            field=models.TextField(blank=True, help_text='Why do you want to rush Lambda Alpha Nu?', null=True, verbose_name='Question 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_2',
            field=models.TextField(blank=True, help_text='Talk about yourself in a couple of sentences.', null=True, verbose_name='Question 2'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_3',
            field=models.TextField(blank=True, help_text='What is your major and why did you choose it?', null=True, verbose_name='Question 3'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_4',
            field=models.TextField(blank=True, help_text='What do you do in your spare time?', null=True, verbose_name='Question 4'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_5',
            field=models.TextField(blank=True, help_text='Talk about a current event in technology and why it interests you.', null=True, verbose_name='Question 5'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_6',
            field=models.TextField(blank=True, help_text='Impress us.', null=True, verbose_name='Question 6'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question_7',
            field=models.TextField(blank=True, help_text='If you were to work on a personal project this semester that you could put on your resume, what would it be? (ex: an iOS app that is Tinder for dogs)', null=True, verbose_name='Question 7'),
        ),
    ]
