# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20170222_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'Strong No'), (2, 'Weak No'), (3, 'Neutral'), (4, 'Weak Yes'), (5, 'Strong Yes')], default=3, verbose_name='Rating'),
        ),
    ]
