# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 22:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go',
            name='id',
            field=models.CharField(error_messages={'unique': 'A Go Link with that ID already exists.'},
                                   help_text='Required. 255 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                   max_length=255, primary_key=True, serialize=False, unique=True, validators=[
                    django.core.validators.RegexValidator('[^a-zA-Z0-9_]+',
                                                          'Enter a valid Go ID. This value may contain only letters, numbers and @/./+/-/_ characters.')],
                                   verbose_name='ID for Go'),
        ),
        migrations.AlterField(
            model_name='go',
            name='url',
            field=models.CharField(help_text='Required. 255 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                   max_length=255, validators=[
                    django.core.validators.RegexValidator('(https?|ftp)://(-\\.)?([^\\s/?\\.#-]+\\.?)+(/[^\\s]*)?$@i',
                                                          'Enter a valid Go URL.')], verbose_name='URL'),
        ),
    ]
