# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 22:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('go', '0002_auto_20160731_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go',
            name='url',
            field=models.CharField(help_text='Required. 255 characters or fewer.', max_length=255, validators=[
                django.core.validators.RegexValidator('(https?|ftp)://(-\\.)?([^\\s/?\\.#-]+\\.?)+(/[^\\s]*)?$@i',
                                                      'Enter a valid Go URL.')], verbose_name='URL'),
        ),
    ]
