# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 05:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='Start Time')),
                ('endTime', models.DateTimeField(verbose_name='End Time')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_url', models.CharField(max_length=255, verbose_name='Image URL')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('event_tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Event Tag'), size=None, verbose_name='Event Tags')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
