# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
