# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_auto_20160815_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presented_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
