# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('is_open', models.BooleanField(default=True, verbose_name='Is Open')),
            ],
        ),
    ]
