# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160731_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes', verbose_name='Resume'),
        ),
    ]
