# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20160822_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='concentration',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('D', 'Design'), ('B', 'Business'),
                                                        ('EE', 'Electrical Engineering'), ('M', 'Math'),
                                                        ('O', 'Other')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non - binary'),
                                                        ('P', 'Prefer not to answer')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
