# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20170115_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='concentration',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('D', 'Design'), ('B', 'Business'),
                                                        ('EE', 'Electrical Engineering'), ('M', 'Math'),
                                                        ('O', 'Other')], default='CS', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non - binary'),
                                                        ('P', 'Prefer not to answer')], default='M', max_length=1,
                                   null=True),
        ),
    ]
