# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170118_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='concentration',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('D', 'Design'), ('B', 'Business'), ('EE', 'Electrical Engineering'), ('M', 'Math'), ('MIS', 'Management Information Systems'), ('O', 'Other')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non - binary'), ('P', 'Prefer not to answer')], default='P', max_length=1),
        ),
    ]
