# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_lan_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lan_class',
            field=models.CharField(blank=True, choices=[('F', 'Founder'), ('A', 'Alpha'), ('B', 'Beta'), ('G', 'Gamma'), ('D', 'Delta'), ('E', 'Epsilon'), ('Z', 'Zeta')], max_length=3, null=True),
        ),
    ]
