# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-21 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180706_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lan_class',
            field=models.CharField(blank=True, choices=[('F', 'Founder'), ('A', 'Alpha'), ('B', 'Beta'), ('G', 'Gamma'), ('D', 'Delta'), ('E', 'Epsilon'), ('Z', 'Zeta'), ('Et', 'Eta'), ('T', 'Theta')], max_length=3, null=True),
        ),
    ]
