# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rush_open', models.BooleanField(default=False, verbose_name='Is rush open')),
                ('voting_status', models.CharField(choices=[('C', 'Closed'), ('A', 'Applications'), ('X', 'Applications Closed'), ('V', 'Voting'), ('R', 'Results')], default='C', max_length=1, verbose_name='Voting Status')),
            ],
        ),
    ]
