# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-21 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20170223_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='voting_status',
            field=models.CharField(choices=[('C', 'Closed'), ('A', 'Applications Open'), ('X', 'Applications Closed'), ('V', 'Voting'), ('D', 'Done')], default='C', max_length=1, verbose_name='Voting Status'),
        ),
    ]
